<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7l9i1YM\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7l9i1YM/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container7l9i1YM.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container7l9i1YM\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container7l9i1YM\App_KernelTestDebugContainer([
    'container.build_hash' => '7l9i1YM',
    'container.build_id' => 'e1a12a93',
    'container.build_time' => 1613933388,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7l9i1YM');
