<?php

namespace Container7l9i1YM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoreServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\StoreService' shared autowired service.
     *
     * @return \App\Service\StoreService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/StoreService.php';

        return $container->privates['App\\Service\\StoreService'] = new \App\Service\StoreService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
