<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVrmoWtE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVrmoWtE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVrmoWtE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVrmoWtE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVrmoWtE\App_KernelDevDebugContainer([
    'container.build_hash' => 'VrmoWtE',
    'container.build_id' => '815812ac',
    'container.build_time' => 1613991910,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVrmoWtE');
