<?php

namespace ContainerG5h8Lmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CheckCommand' shared autowired service.
     *
     * @return \App\Command\CheckCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CheckCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Utils/Challenge.php';

        $container->privates['App\\Command\\CheckCommand'] = $instance = new \App\Command\CheckCommand(($container->privates['App\\Service\\RequestService'] ?? $container->load('getRequestServiceService')), ($container->privates['App\\Utils\\Challenge'] ?? ($container->privates['App\\Utils\\Challenge'] = new \App\Utils\Challenge())));

        $instance->setName('url:check');

        return $instance;
    }
}
