<?php

namespace ContainerG5h8Lmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RequestService' shared autowired service.
     *
     * @return \App\Service\RequestService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RequestService.php';

        return $container->privates['App\\Service\\RequestService'] = new \App\Service\RequestService(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), ($container->privates['App\\Repository\\RequestRepository'] ?? $container->load('getRequestRepositoryService')), ($container->privates['App\\Repository\\OcurrenceRepository'] ?? $container->load('getOcurrenceRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
